install updates, sha1, etc

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,8 +1,7 @@
 #!/usr/bin/env bash
 
 # TODO: add to apt/get + other functions: (and change glances to -ol only)
-#       -oc -ol -hh -hw
-# TODO: add mplayer files to links
+#       -oc -ol -oh -ow
 # TODO: create functions: LOG_ERROR, LOG_INFO
 # TODO: fzf - cancel interactive script! provide Y
 # TODO: change aptget: use apt-cache to check if it's updated or older version. If older, then update it.
@@ -53,6 +52,7 @@ __myhost="$(uname -n)"
                     ;;
                 *)
                     __myos="OTHER"
+                    __myhost="OTHER"
                     ;;
             esac
 __dir_dlocal="$(cd "$(dirname "${__dir}")" && pwd)/dotfiles.local"
@@ -94,6 +94,70 @@ mkdir -p ~/.emacs.d/mine
     mkdir -p ${__win_appdata}/.emacs.d/mine
 find ${__dir}/bin -type f -not -name 'create_bash.model' -exec chmod +x {} \;
 find ${__dir} -maxdepth 1 -type f -not -name 'install' -exec chmod -x {} \;
+
+# --------------------------------------------------------------------------------
+# checksum - return 0 if sum is ok
+# $1 = file to check the sum
+# $2 =
+#      -sha1 [SHA1SUM]
+# RETURN VALUES
+#    1 = wrong SUM!
+# <> 1 = other errors
+checksum()
+{
+    local file=""
+    local sum_type
+    local sum_value
+    while [[ $# > 0 ]]; do
+        case "$1" in
+            -sha1) # sum type
+                shift
+                sum_value="$1"
+                sum_type="sha1"
+                shift
+                ;;
+            *) # file name to check
+                if [[ -n "${file}" ]]; then
+                    echo "===[SUM] ERROR: Unknown second option? (${file})"
+                    __errors+=("[SUM] ERROR: Unknown second option? (${file})")
+                    return 3
+                fi
+
+                file="$1"
+                shift
+
+                if [[ ! -f "${file}" ]]; then
+                    echo "===[SUM] ERROR: File does not exist: ${file} (or is not a file)"
+                    __errors+=("[SUM] ERROR: File does not exist: ${file} (or is not a file)")
+                    return 2
+                fi
+                ;;
+        esac
+    done
+
+    # CHECK SUM:
+    case "${sum_type}" in
+        sha1)
+            sha1sum --status -c <(echo "${sum_value}" "${file}") \
+                ||
+                {
+                    echo "===[SUM] ERROR: Wrong checksum for: ${file}"
+                    __errors+=("[SUM] ERROR: Wrong checksum for: ${file}")
+                    return 1
+                } \
+                &&
+                {
+                    echo "===[SUM] CHECKSUM OK: ${file}"
+                    return 0
+                }
+            ;;
+        *)
+            echo "===[SUM] ERROR: Unknown sum type: ${sum_type}"
+            __errors+=("[SUM] ERROR: Unknown sum type: ${sum_type}")
+            return 4
+            ;;
+    esac
+}
 
 
 # --------------------------------------------------------------------------------
@@ -226,9 +290,19 @@ aptget()
     fi
 
     local install_cmd="${__aptget_install_cmd} ${app_install}"
-    echo "===[A] Installing: ${install_cmd}..."
-    ${install_cmd}
-    echo "===[A] Done."
+    echo "===[A] Installing..."
+    ${install_cmd} \
+        ||
+        {
+            echo "===[A] ERROR: installing ${app_install}"
+            __errors+=("[A] ERROR: installing ${app_install}")
+            return 1
+
+        } \
+        &&
+        {
+            echo "===[A] Done."
+        }
 }
 
 
@@ -266,33 +340,54 @@ gitclone()
 
 
 # --------------------------------------------------------------------------------
-# geturl
-# $1  = options
-#       -u  :: update (delete the file/folder and redownload it)
-# $1  = url to download
-# $2  = filename to save as
-# $3- = cmds to run after downloading
-
+# geturl [OPTIONS] <URL> <FILE> [OPTIONS] [RUN_LATER]
+# OPTIONS:
+#     -u    :: update (delete the file/folder and redownload it)
+#     -d    :: delete the file bofore downloading and after succussful install
+#     -sha1 <SUM> :: sha1sum of the file to check. If it fails, file is not installed
 geturl()
 {
     local update=""
-    local url
-    local file
+    local url=""
+    local file=""
+    local sum_type=""  # for checksum()
+    local sum_value="" # for checksum()
+    local if_moved_to_tmpfile=0
+    local if_del=0
+
     while [[ $# > 0 ]]; do
         case "$1" in
             -u)
                 shift
                 update="Y"
                 ;;
+            -d)
+                shift
+                if_del=1
+                ;;
+            -sha1)
+                shift
+                sum_value="${1}"
+                sum_type="sha1"
+                shift
+                ;;
             *)
-                break;
+                if [[ -z "${url}" ]]; then
+                    url="${1}"
+                    shift
+                elif [[ -z "${file}" ]]; then
+                    file="${1}"
+                    shift
+                else
+                    break
+                fi
                 ;;
         esac
     done
-    url="${1}"
-    file="${2}"
-    shift
-    shift
+    if [[ ${if_del}=1 ]]; then
+        rm -rf "${file}"
+    fi
+
     local runlater=("$@")
     tmpfile="${file}#.#"
 
@@ -307,30 +402,56 @@ geturl()
 
     if [[ "${update}" = "Y" && -e ${file} ]]; then
         mv "${file}" "${tmpfile}"
+        if_moved_to_tmpfile=1
     elif [[ -e ${file} ]]; then
-        echo "===[U] File/dir already exists: ${file}"
+        echo "===[U] File/dir already exists: ${file} . Not redownloading."
         return 0
     fi
 
+    # download:
     echo "===[U] Downloading ${url}..."
-    ${__geturl_app} ${file} ${url} ||
+    ${__geturl_app} ${file} ${url} \
+        ||
         {
-            echo -n "===[U] ERROR downloading file: ${url} . Restoring old one... "
+            echo "===[U] ERROR downloading file: ${url}"
             __errors+=("[U] ERROR downloading file: ${url}")
-            mv ${tmpfile} ${file}
-            echo "Done."
+            if [[ ${if_moved_to_tmpfile} = 1 ]]; then
+                echo -n "===[U] Restoring old one... "
+                mv -f ${tmpfile} ${file}
+                echo "Done."
+            fi
             return 1
         }
 
+    # check sum:
+    if [[ -n ${sum_type} ]]; then
+        checksum ${file} -${sum_type} ${sum_value} ||
+            {
+                echo "===[U] ERROR checksum: not installing: ${url}"
+                __errors+=("[U] ERROR checksum: not installing: ${url}")
+                if [[ ${if_moved_to_tmpfile} = 1 ]]; then
+                    echo -n "===[U] Restoring old one... "
+                    mv -f ${tmpfile} ${file}
+                    echo "Done."
+                fi
+                return 1
+            }
+    fi
+
     echo "===[U] Done."
-    if [[ "${update}" = "Y" && -e ${tmpfile} ]]; then
+    if [[ ${if_moved_to_tmpfile}=1 && -e ${tmpfile} ]]; then
         rm -rf "${tmpfile}"
     fi
 
+    cd "$(cd "$(dirname "${file}")" && pwd)"
     for run in "${runlater[@]:-}" ; do
         echo "===[U] run ${run}"
         ${run}
     done
+
+    if [[ ${if_del}=1 ]]; then
+        rm -rf "${file}"
+    fi
 
 }
 
@@ -557,9 +678,9 @@ install_more_apps()
     aptget emacs || true
     if hash emacs 2>/dev/null; then
         # evil-leader:
-        geturl https://raw.githubusercontent.com/cofi/evil-leader/master/evil-leader.el ~/.emacs.d/mine/evil-leader.el || true
+        geturl https://raw.githubusercontent.com/cofi/evil-leader/master/evil-leader.el ~/.emacs.d/mine/evil-leader.el -sha1 00c336e55307dbcb3f73f47b1d9a1d759404341d || true
         # key-chord:
-        geturl http://www.emacswiki.org/emacs/download/key-chord.el ~/.emacs.d/mine/key-chord.el || true
+        geturl http://www.emacswiki.org/emacs/download/key-chord.el ~/.emacs.d/mine/key-chord.el -sha1 2da61bf970ca332c4de96c1977fc7e326df6c33a || true
         # evil:
         gitclone https://gitorious.org/evil/evil.git ~/.emacs.d/evil \
             ||
@@ -595,10 +716,12 @@ install_more_apps()
     gitclone https://github.com/VitaliyRodnenko/geeknote.git ~/apps/geeknote "${__sudo} python setup.py install" "geeknote settings --editor vim" || true
 
     # glances
-    aptget glances || true
-      # for glances:
-      aptget lm-sensors || true
-      pipinstall -2 PySensors
+    aptget glances \
+        &&
+        {
+            aptget lm-sensors || true
+            pipinstall -2 PySensors
+        } || true
 
     # Reszta 2:
     pipinstall -3 BeautifulSoup4
@@ -634,28 +757,37 @@ install_basics()
     aptget vim || true
     aptget make || true
     gitclone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim || true
-    aptget python-pip pip \
-        ||
-        {
-            geturl https://bootstrap.pypa.io/get-pip.py /tmp/get-pip.py "sudo python2 get-pip.py" "rm get-pip.py"
-        }
-    aptget python3-pip pip3 \
-        ||
-        {
-            geturl https://bootstrap.pypa.io/get-pip.py /tmp/get-pip.py "sudo python3 get-pip.py" "rm get-pip.py"
-        }
+    if hash python2 2>/dev/null; then
+        aptget python-pip pip \
+            ||
+            {
+                geturl https://bootstrap.pypa.io/get-pip.py /tmp/get-pip.py -sha1 89eb61fc5b59f14df7f0aa7b020afb5a6ded2e14 "sudo python2 get-pip.py" "rm get-pip.py"
+            }
+    fi
+
+    if hash python3 2>/dev/null; then
+        aptget python3-pip pip3 \
+            ||
+            {
+                geturl https://bootstrap.pypa.io/get-pip.py /tmp/get-pip.py -sha1 89eb61fc5b59f14df7f0aa7b020afb5a6ded2e14 "sudo python3 get-pip.py" "rm get-pip.py"
+            }
+    fi
 
     # Ranger
     # rm -rf ~/apps/ranger ~/.config/ranger
     gitclone https://github.com/hut/ranger.git ~/apps/ranger "${__sudo} make install" "ranger --copy-config=all" || true
 
     # TMUX
-    aptget tmux
+    aptget tmux || true
 
     # Reszta 1:
-    aptget wget && __geturl_app="wget -O"
-    aptget curl && __geturl_app="curl -o"
-    aptget dtrx
+    aptget wget && __geturl_app="wget -O" || true
+    aptget curl && __geturl_app="curl -o" || true
+    aptget dtrx ||
+        {
+            rm -rf /tmp/dtrx-7.1
+            geturl -d http://brettcsmith.org/2007/dtrx/dtrx-7.1.tar.gz /tmp/dtrx-7.1.tar.gz -sha1 05cfe705a04a8b84571b0a5647cd2648720791a4 "tar -xf dtrx-7.1.tar.gz" "cd dtrx-7.1" "${__sudo} python setup.py install --prefix=/usr/local" "rm -rf /tmp/dtrx-7.1" "rm -rf /tmp/dtrx-7.1.tar.gz"
+        }
 
     # fasd
     gitclone https://github.com/clvv/fasd.git ~/apps/fasd "${__sudo} make install" || true
@@ -725,6 +857,19 @@ while [[ $# > 0 ]]; do
             ;;
     esac
 done
+
+# # start
+# aptget dtrx ||
+#     {
+#         echo "byl blad"
+#         geturl -d http://brettcsmith.org/2007/dtrx/dtrx-7.1.tar.gz /tmp/dtrx-7.1.tar.gz -sha1 05cfe705a04a8b84571b0a5647cd2648720791a4 "tar -xf dtrx-7.1.tar.gz" "cd dtrx-7.1" "python setup.py install --prefix=/usr/local" "rm -rf /tmp/dtrx-7.1"
+#     } &&
+#         {
+#             echo nie bylo bledu
+#         }
+# echo "=============== END DTRX"
+# exit
+# # end
 
 [[ ${if_break_links} = "Y" ]] && break_links
 
