os

diff --git a/os_linux_install b/os_linux_install
--- a/os_linux_install
+++ b/os_linux_install
@@ -6,16 +6,38 @@ set -o nounset
 # set -o xtrace
 
 # Set magic variables for current file & dir
-__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
 __dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
 # __base="$(basename ${__file} .sh)"
 # __root="$(cd "$(dirname "${__dir}")" && pwd)"
 
 # magic variables for links
-__file="$(readlink -f ${BASH_SOURCE[0]})"
-__dir="$(cd "$(dirname "${__file}")" && pwd)"
+#__file="$(readlink -f ${BASH_SOURCE[0]})"
+#__dir="$(cd "$(dirname "${__file}")" && pwd)"
 
 arg1="${1:-}"
 
-sudo apt-get -qyf install python-pip
+
+install()
+{
+    app=
+    local instalcmd
+    if hash sudo 2>/dev/null; then
+        instalcmd="sudo "
+    fi
+    if hash apt-get 2>/dev/null; then
+        instalcmd="${instalcmd}apt-get -qyf "
+    fi
+    if [[ -z $1 ]]; then
+        echo "Error: Bledny parametr"
+        exit 1
+    else
+        instalcmd="${instalcmd}${1}"
+        echo "${instalcmd}"
+    fi
+}
+
+install "abc"
+
+# sudo apt-get -qyf install python-pip
 
